# Generated by Django 2.2.7 on 2019-11-14 14:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("position_title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("facade_image", models.ImageField(upload_to="")),
                ("position", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("employees", models.ManyToManyField(to="core.Employee")),
            ],
        ),
    ]
