# Generated by Django 2.2.7 on 2019-11-14 14:25
import json
import os

from django.contrib.gis.geos import Point
from django.core.files import File
from django.db import migrations

from libertex.settings import BASE_DIR


def load_init_data(apps, schema_editor):
    Employee = apps.get_model("core", "Employee")
    with open(os.path.join(BASE_DIR, "mock_data", "employees.json"), "r") as f:
        _employees = json.load(f)

    employees = []
    for _employee in _employees:
        employee = Employee.objects.create(**_employee)
        employees.append(employee)

    Branch = apps.get_model("core", "Branch")
    with open(os.path.join(BASE_DIR, "mock_data", "branches.json"), "r") as f:
        _branches = json.load(f)

    branches = []
    for _branch in _branches:
        image = _branch.pop("facade_image")
        position = _branch.pop("position")
        _branch.update({"position": Point(position[0], position[1], srid=4326)})
        branch = Branch.objects.create(**_branch)
        branch.facade_image.save(
            image, File(open(os.path.join(BASE_DIR, "mock_data", image), "rb"))
        )
        # branch.position = Point(position[0], position[1], srid=4326)
        branch.save()
        branches.append(branch)

    for i in range(10):
        branch = branches[i]
        branch.employees.set(employees[i * 1000 : i * 1000 + 1000])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_init_data)]
